name: Build and Deploy from [main] branch to [gh-pages] branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite
        run: npm run build
        env:
          VITE_KAKAOMAP_KEY: ${{ secrets.VITE_KAKAOMAP_KEY }}

      - name: Copy files
        run: cp -r src/assets/images docs/

      - name: set git user email
        run: git config user.email "okyb0309@gmail.com"

      - name: set git user email
        run: git config user.email "okyb0309@gmail.com"

      - name: Deploy to hosting (e.g., GitHub Pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs  # Set to your build output directory
